ALTER TABLE customer
ADD COLUMN router int NOT NULL,
ADD COLUMN action int NOT NULL,
ADD COLUMN auto_isolir int NOT NULL,
ADD COLUMN codeunique int NOT NULL,
ADD COLUMN phonecode int NOT NULL,
ADD COLUMN type_id varchar(50) NOT NULL,
ADD COLUMN user_mikrotik varchar(50) NOT NULL,
ADD COLUMN mode_user varchar(50) NOT NULL,
ADD COLUMN user_profile varchar(50) NOT NULL,
ADD COLUMN type_payment int NOT NULL,
ADD COLUMN max_due_isolir int NOT NULL,
ADD COLUMN latitude text NOT NULL,
ADD COLUMN longitude text NOT NULL,
;

ALTER TABLE invoice
ADD COLUMN i_ppn int NOT NULL,
ADD COLUMN metode_payment varchar(50) NOT NULL,
ADD COLUMN admin_fee int NOT NULL,
ADD COLUMN amount int NOT NULL,
ADD COLUMN order_id varchar(128) NOT NULL,
ADD COLUMN token text NOT NULL,
ADD COLUMN payment_type varchar(128) NOT NULL,
ADD COLUMN transaction_time varchar(128) NOT NULL,
ADD COLUMN bank varchar(128) NOT NULL,
ADD COLUMN va_number varchar(128) NOT NULL,
ADD COLUMN pdf_url text NOT NULL,
ADD COLUMN expired text NOT NULL,
ADD COLUMN status_code varchar(128) NOT NULL,
ADD COLUMN x_id varchar(128) NOT NULL,
ADD COLUMN x_bank_code varchar(128) NOT NULL,
ADD COLUMN x_method varchar(128) NOT NULL,
ADD COLUMN x_account_number varchar(128) NOT NULL,
ADD COLUMN x_expired varchar(128) NOT NULL,
ADD COLUMN x_external_id varchar(128) NOT NULL,
ADD COLUMN x_amount varchar(128) NOT NULL,
ADD COLUMN x_qrcode varchar(128) NOT NULL,
ADD COLUMN reference text NOT NULL,
ADD COLUMN payment_url text NOT NULL,
ADD COLUMN code_coupon varchar(128) NOT NULL,
ADD COLUMN status_income varchar(128) NOT NULL,
ADD COLUMN disc_coupon varchar(128) NOT NULL,
ADD COLUMN outlet varchar(128) NOT NULL,
;